language: node_js
dist: trusty
git:
  depth: 1
cache:
  edge: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "DjAPSgTp76GMNHzAyNeBswqDTUc9NOUepL3JgzxOj23qMv09KzBQ3kIm1hsEn5ynceqd7ltiQt5DUyQDcYZGlfZab4aWTZZ/eZoy7qGDbn48dq08mdylmUbe9UAn+EsS9jQNTW9EoCUr8Zyi/uG/EJiPOTXqzXNdakPoscNhhexTuu8vcz+Vk95XrJ6sNkSmfmM4G9bqwtCNs6sjKEPW7ryEY1Csfm90os0OR0rDiJUkKtTadGHkK5njGzgDadThpFCsx++we15TFcC2QIaxX+Ju04Dy9sOtA9p124n8f/R4KOL6+tCIYjbaJc9fX97pdAIZUexFJTkUrvyGU3iHAU3ZbY+ViDQBa7i0fxlMxuyU6rhUb0xT2PUjKbuT6b4rVtFSkzhxdec8yLQwOoxJybNlA+j1xC1d+hkR+XieU50To/foxQsk5x8YhzZQRT43jcRDYLRBX5++o8rGVaEP5xV2Hj3j6tU1UuaDb6W8osG+PjGQE97mlgA9dJb3qpm/E+5U0B7wLkRBOtcRznKVhyJvcJAFcpz/i4avtt2n08XTpLBZt6HMPwExlgTZ+UVu7DLgQYwxoGHxzw7I0iYqqY0X4fB2m185iWM62OE8h+ZYi7Z8/Qf+7NMlbX6YOoKrNOFyt4qL73MAExxkmy6facKOvEBI9ohFlQYjq5Y1jlw="
    # SNYK_API_TOKEN=[secure]
    - secure: "IhHy8AeNa9FC5UrNueGc8vFqX+z0e3v/t1R3vLcJRA+ILoRlnTtmuWMSATIfwPAAsrZt+Y5JKGHGRat/7sY7Q3Dh4HPax1SD4ljUt6r9HQsYTggoQCEsr+H/+irsPTHTMIw034WzF9J7JIogIiHdnUtfNY+IM+GgqOwA06Sb7aE9jUjkKqEto47jpXRdrMLfKMClg5zu9SQ66VPkrnWwDdn03H0/34DTEbd16L2sTSR+Drj/4BQjn0t0mu2MunlbseiRazZGRkzHOI4jzEuQ4WB3CPY3x/B1yHHfUyIowlbmOT24Z9QEy2+1bfhuDGj4pMFK5R0JdZxjXaDqh4N5GYpOH7z5jFK+13iLuslAJ+V0HcGDM+P/s60g50hg3wLFV88vID8no+dRzLrzPS83MAEh22y8LzyVWOQ8g5i6rXjJQ8U4Yz/2y/lJes7BoTOoZBvXNyjF0EMbRtlGGbyxMYWd0vQrIJLePckJT2wkRb56hqGtBXyfxky+IL3ikBX4rZiK7sFYFRuf5Fky89AzE2bpz0IR0PCKt0ICHLbvK1VlC+hLNOqBNkZPnNDUjVMhxvr4u+e3hiYBHeB3iLFZxh8oJ1swBzNNJCMHlFwpDpM1S9SL2FF/Oo7rLpzexF51dabdfO9+9+/fp4B/QqD6ShNYKE6s6guJRIMBa5S0wYs="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "ellfP0RLlWazpiYq3Lz7DfdSwGFdNBcWYZInEYzmxyl5yCPGDGXizMF48QXbDIUDrk/HIfMhwOns//rCnnnghPomVub9DQfVo+yKofiNEP8QcTRTT+N3pNdQxP2YdnhAWtY7sxrbjtJu+hbOvIxwcL3dGFkqLxX1lOr5LKYpS4V4f+JUWtCiXbDlzJ6SeTuwraF7JwDpESngC7m/xTPqv5jrH4s8Xp2LRLrGFoXe6M7Yn+6jYBOwRxgFVHzdeOaSkGGrviOhCuW12erj6wBTw2sKxh+q64Af3CFhJ61S4+qp8GCsIB5p+qQci4rfPE6hDzCjqfKzFAH8YYM3nMhPQ/o/iOG9U0Z8BsiTgf3+CGfc6cpLWaz9X2ucJcX7Yv9OkssiA+QHvbpxpDXEOAJJjQwSkUWNc7hCRjXgXTvlQ4Ki71OB4xglDb1/KVarKxh37ywAqOwHv2qWaZJd6Gn4GpQE01Wf5Ej/LH1ivWYgxYfv6/WLbWJ5HGvvPawVJ5ocwa4OOLOtIsWiDeGgRCxPp+WguzDm4L1po2OWyJ/seE4IshdF7anUM+0CVLEPGAWgSDdroeJKznUPwosOI6ee1cY7pUgj6K69MCvggSiO6q4AI364cTZQWQQpJe+N4KvXkwOgCfG5h34YMCy7+CxyA1ZDRFvzmAsTlijfAWfI05s="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "GhEMkWJa4A/jCEfP/f/PS+2xaHqgXWbPfzLPrcfWleV+M+Kv/gtkoBsQ63qqracTYi68M3Ew3e3Ug5AU4dgieITk1koe90NFtz9ezk6TP+5MPm4iUFVn37XAILWs2lzKorRkTqjKLEUJezzazY0TU2R3u/hM7hYrlOsPY9j0KLmi4UGNasCIScNuo3ZDCk53Lthea1FR/imnZi3niVblILFRCQ4xjJcH4DoHqSeBoJuddqE0luOacSunaJkqBV2Dnla+uLOJWx/JW42R08nsKTxhkZn8GX5NrCdG+VFTdeJIUgIVcm3hw29m6/MZFnxR2cQJXibbeWf1zA5sEif0vo39mPf7Nj6MJHZwFBHil+NVrVfA0X0QYE3kxLBsWCYJAK6l/ZisNp5g6mVuTY8xb8+isU01PjWH+jklqfwocmJGQWBqOjifUIalTk04QevkczFl4scAjM15zLTGI/xeU+b+EKHesLbJQ2+VKk4ZQFTmFQ+bYo8qrHtqb+CGvPE6/ikd1zmG0wrfw+zaXQxwcDlhbKZZQZ7su3z/z9uilPo9ftSOXtmI710veWja08E/0U23II9BD+wOxS+2PnOwipjc6h+MqgRdDNJLOej0BiM6Ia8j0Q6MLgNmPKu27InwVjfzL4+2w55WLUuWSOR91Pjsea/X0zwBzKNvOtZiiEI="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "dPfPZXljddRPnESbqA4efUqkTYioZOMGeS2iNivbSjrMTlGpvgruujRNWP0hcicWuNVx/JubepL/gNwvX8qTbCxNLym9fol0MzRLrz2OluEUJY2xk6yJvNer8LrQxXRson5AHXNjU7nIH3gUnV+D/ZZh90TvjDv+mpu/yOqOh7+WSfvOXAi1OgFbrvS49uADutZHhElmytuf53jqQxp5PV14wBXAOwiv3mYxWQw4rCLddVPX+tcBOU7aCeegR68otfMQWCISKzor4cmrEXHppOcw4Vvn8/Whqox7YL3M9TPybA04j4Rfipf2G0ERvv9OJ1owjgF1CD1aqTuBbvaUyF4+U4uM577J8vcF+2avgrhNjpznMc8HviY356q/cOa92R/e6zU+q7LQ8ZTADyuEI+bsetrmYUQvG8vq8vDHJJ29uZ5961knZKrjuhWVGiI7ORVtxu7AKAThXtpM+LW79lwWhqi5ILLzmpX3Km+VS6KHvPOWwFzccX9e2cl3DAP/6ue8K8E/UGqpuQhMcLtF37N2jDbwsMUxDbv+SveP9pqbdgTM4k1Yb7pcDdByvOS6j86VjnaAnemWeS7kmUuPxzYgMtS6G6nCy9KteSCx3ddqYW/2JNaDBHg2YocTIRAdHB5DGuvu0qVvhfhrrIvQH8g9iZeuV8VGPNXDT7x3ZFw="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - bash bin/travis-init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk
